Controllers/HomeController.cs
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using MyResumeSite.Models;
using System.Collections.Generic;
using Umbraco.Web;
using Umbraco.Core.Models;
using System.Linq;
using Archetype.Models;
using Newtonsoft.Json;
using System;
using Umbraco.Core;

namespace MyResumeSite.Controllers
{
    public class HomeController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/Home/";

        public ActionResult RenderCover()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Cover.cshtml");
        }

        public ActionResult RenderAbout()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_About.cshtml");
        }

        public ActionResult RenderResume()
        {
            List<Timeline> timelineList = new List<Timeline>();
            IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            ArchetypeModel timelineCategories = homePage.GetPropertyValue<ArchetypeModel>("timeline");
            foreach(ArchetypeFieldsetModel fieldset in timelineCategories)
            {
                //CATEGORY FROM TIMELINE
                string category = fieldset.GetValue<string>("timelineCategory");
                if (!String.IsNullOrEmpty(category))
                {                    
                    //var timelineItems = JsonConvert.DeserializeObject<ArchetypeModel>(fieldset.GetValue<string>("timelineItems"));
                    var timelineItems = JsonConvert.DeserializeObject<ArchetypeModel>(fieldset.Properties.Where(x => x.Alias == "timelineItems").FirstOrDefault().Value.ToString());                    
                    List<TimelineItem> listItems = new List<TimelineItem>();
                    foreach (ArchetypeFieldsetModel itemFieldset in timelineItems)
                    {
                        string itemHeader = itemFieldset.GetValue<string>("timelineItemHeader");
                        string itemSubHeader = itemFieldset.GetValue<string>("timelineItemSubHeader");
                        string itemContent = itemFieldset.GetValue<string>("timelineItemContent");
                        string itemIcon = itemFieldset.GetValue<string>("timelineItemIcon");
                        List<ModalContent> itemModals = new List<ModalContent>();
                        if (!string.IsNullOrEmpty(itemFieldset.GetValue<string>("timelineItemModals")))
                        {
                            var timelineItemModals = JsonConvert.DeserializeObject<ArchetypeModel>(itemFieldset.GetValue<string>("timelineItemModals"));
                            //ArchetypeModel timelineItemModals = itemFieldSet.GetValue<ArchetypeModel>("timelineItemModals");                        
                            foreach (ArchetypeFieldsetModel itemModalFieldSet in timelineItemModals)
                            {
                                string modalTitle = itemModalFieldSet.GetValue<string>("modalTitle");
                                string modalContent = itemModalFieldSet.GetValue<string>("modalContent");
                                itemModals.Add(new ModalContent(modalTitle, modalContent));
                            }
                        }
                        listItems.Add(new TimelineItem(itemHeader, itemSubHeader, itemContent, itemIcon, itemModals));
                    }
                    timelineList.Add(new Timeline(category, listItems));
                }
            }
            string resumeTitle = Umbraco.AssignedContentItem.GetPropertyValue("resumeTitle").ToString();
            return PartialView(PARTIAL_VIEW_FOLDER + "_Resume.cshtml",new Tuple<List<Timeline>, string>(timelineList,resumeTitle));
        }

        public ActionResult RenderSkills()
        {
            List<SkillCollection> model = new List<SkillCollection>();
            IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            ArchetypeModel skills = homePage.GetPropertyValue<ArchetypeModel>("skillsCollection");
            foreach (ArchetypeFieldsetModel fieldset in skills)
            {
                string category = fieldset.GetValue<string>("skillCategory");
                if (!String.IsNullOrEmpty(category))
                {                    
                    var skillItems = JsonConvert.DeserializeObject<ArchetypeModel>(fieldset.Properties.Where(x => x.Alias == "skillItems").FirstOrDefault().Value.ToString());
                    List<SkillItem> listItems = new List<SkillItem>();
                    foreach (ArchetypeFieldsetModel itemFieldset in skillItems)
                    {
                        string itemTitle = itemFieldset.GetValue<string>("skillTitle");
                        int itemRange = Convert.ToInt32(Umbraco.GetPreValueAsString(itemFieldset.GetValue<int>("skillRange")));                        
                        listItems.Add(new SkillItem(itemTitle,itemRange));
                    }
                    model.Add(new SkillCollection(category, listItems));
                }
            }
            string skillsTitle = Umbraco.AssignedContentItem.GetPropertyValue("skillsTitle").ToString();
            string extraSkills = Umbraco.AssignedContentItem.GetPropertyValue("extraSkills").ToString();
            List<string> parmSkills = new List<string>();
            parmSkills.Add(skillsTitle);
            parmSkills.Add(extraSkills);
            return PartialView(PARTIAL_VIEW_FOLDER + "_Skills.cshtml",new Tuple<List<SkillCollection>,List<string>>(model, parmSkills));
        }

        public ActionResult RenderPersonalAchievements()
        {
            List<ImageLibrary> model = new List<ImageLibrary>();
            IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            ArchetypeModel imageLibrary = homePage.GetPropertyValue<ArchetypeModel>("personalAchievementImages");
            foreach (ArchetypeFieldsetModel fieldset in imageLibrary)
            {
                string imageFullGuid = fieldset.Properties.Where(x => x.Alias == "imageLibraryImage").FirstOrDefault().Value.ToString();
                string imageFullUrl = "";
                if (!String.IsNullOrEmpty(imageFullGuid))
                {
                    Udi imageFullUdi = Udi.Parse(imageFullGuid);
                    int imageFullId = Umbraco.GetIdForUdi(imageFullUdi);
                    var imageFull = Umbraco.Media(imageFullId);
                    imageFullUrl = imageFull.Url;
                }
                string imageThumbGuid = fieldset.Properties.Where(x => x.Alias == "imageLibraryThumb").FirstOrDefault().Value.ToString();
                string imageThumbUrl = "";
                if (!String.IsNullOrEmpty(imageThumbGuid))
                {
                    Udi imageThumbUdi = Udi.Parse(imageThumbGuid);
                    int imageThumbId = Umbraco.GetIdForUdi(imageThumbUdi);
                    var imageThumb = Umbraco.Media(imageThumbId);
                    imageThumbUrl = imageThumb.Url;
                }
                string imageDescription = fieldset.GetValue<string>("imageLibraryDescription");
                string imageTitle = fieldset.GetValue<string>("imageLibraryTitle");
                model.Add(new ImageLibrary(imageTitle,imageDescription,imageThumbUrl, imageFullUrl));
            }
            string achTitle = Umbraco.AssignedContentItem.GetPropertyValue("personalAchievementsTitle").ToString();
            return PartialView(PARTIAL_VIEW_FOLDER + "_PersonalAchievements.cshtml",new Tuple<List<ImageLibrary>,string>(model,achTitle));
        }

        public ActionResult RenderEntrepreneurialExperiences()
        {
            List<ImageShow> model = new List<ImageShow>();
            IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            ArchetypeModel imageShowCollection = homePage.GetPropertyValue<ArchetypeModel>("xpImageCollection");
            foreach (ArchetypeFieldsetModel fieldset in imageShowCollection)
            {
                string imageGuid = fieldset.Properties.Where(x => x.Alias == "image").FirstOrDefault().Value.ToString();
                Udi imageUdi = Udi.Parse(imageGuid);                
                int imageId = Umbraco.GetIdForUdi(imageUdi);
                var image = Umbraco.Media(imageId);
                string imageUrl = image.Url;
                string imageDescription = fieldset.GetValue<string>("imageDescription");
                model.Add(new ImageShow(imageUrl, imageDescription));
            }
            string xpTitle = Umbraco.AssignedContentItem.GetPropertyValue("xpTitle").ToString();
            return PartialView(PARTIAL_VIEW_FOLDER + "_EntrepreneurialExperiences.cshtml",new Tuple<List<ImageShow>,string>(model,xpTitle));
        }

        public ActionResult RenderContact()
        {
            return PartialView(PARTIAL_VIEW_FOLDER + "_Contact.cshtml");
        }
    }
}

Controllers/SiteLayoutController.cs
using MyResumeSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web;
using Umbraco.Web.Mvc;

namespace MyResumeSite.Controllers
{
    public class SiteLayoutController : SurfaceController
    {
        private const string PARTIAL_VIEW_FOLDER = "~/Views/Partials/SiteLayout/";

        public ActionResult RenderNavigation()
        {
            List<NavigationListItem> nav = GetNavigationModelFromDatabase();
            string homeTitle = Umbraco.AssignedContentItem.GetPropertyValue("homeTitle").ToString();
            return PartialView(PARTIAL_VIEW_FOLDER + "_Navigation.cshtml", new Tuple<List<NavigationListItem>,string>(nav,homeTitle) );
        }

        /// <summary>
        /// Finds the home page and gets the navigation structure based on it and it's children
        /// </summary>
        /// <returns>A List of NavigationListItems, representing the structure of the site.</returns>
        private List<NavigationListItem> GetNavigationModelFromDatabase()
        {            
            IPublishedContent homePage = CurrentPage.AncestorOrSelf(1).DescendantsOrSelf().Where(x => x.DocumentTypeAlias == "home").FirstOrDefault();
            List<NavigationListItem> nav = new List<NavigationListItem>();
            //nav.Add(new NavigationListItem(new NavigationLink(homePage.Url, homePage.Name))); //COMMENTED TO DONT INCLUDE HOME ON NAVIGATION
            nav.AddRange(GetChildNavigationList(homePage));
            return nav;
        }

        /// <summary>
        /// Loops through the child pages of a given page and their children to get the structure of the site.
        /// </summary>
        /// <param name="page">The parent page which you want the child structure for</param>
        /// <returns>A List of NavigationListItems, representing the structure of the pages below a page.</returns>
        private List<NavigationListItem> GetChildNavigationList(IPublishedContent page)
        {
            List<NavigationListItem> listItems = null;
            var childPages = page.Children.Where("Visible");
            if (childPages != null && childPages.Any() && childPages.Count() > 0)
            {
                listItems = new List<NavigationListItem>();
                foreach (var childPage in childPages)
                {
                    NavigationListItem listItem;
                    if (childPage.HasProperty("linkUrl"))
                    {
                        listItem = new NavigationListItem(new NavigationLink(childPage.GetPropertyValue("linkUrl").ToString(), childPage.GetPropertyValue("text").ToString(), Convert.ToBoolean(childPage.GetPropertyValue("newWindow")), childPage.GetPropertyValue("title").ToString()));
                    }
                    else
                    {
                        listItem = new NavigationListItem(new NavigationLink(childPage.Url, childPage.Name));
                    }                    
                    listItem.Items = GetChildNavigationList(childPage);
                    listItems.Add(listItem);
                }
            }
            return listItems;
        }

        public ActionResult RenderBottom()
        {            
            return PartialView(PARTIAL_VIEW_FOLDER + "_Bottom.cshtml");
        }
    }
}

Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@
@{Html.RenderAction("RenderCover", "Home");}
@{Html.RenderAction("RenderAbout", "Home");}
@{Html.RenderAction("RenderResume", "Home");}
@{Html.RenderAction("RenderSkills", "Home");}
@{Html.RenderAction("RenderEntrepreneurialExperiences", "Home");}
@{Html.RenderAction("RenderPersonalAchievements", "Home");}
@{Html.RenderAction("RenderContact", "Home");}

Views/Link.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Link>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Views/WebBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using System.Web.Optimization
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Hire Carlos!</title>    

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet"> 
    <!-- Plugin CSS -->
    <link href="/vendor/magnific-popup/magnific-popup.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/css/creative.css" rel="stylesheet">
    <link href="/css/icomoon.css" rel="stylesheet">
    <link href="/css/custom.css" rel="stylesheet">
    <!-- Animate.css -->
    <link rel="stylesheet" href="/css/animate.css">

    <!-- Modernizr JS -->
    @*<script src="/scripts/modernizr-2.6.2.min.js"></script>*@
    @RenderSection("Head",false)
</head>
<body id="page-top">
    @RenderSection("ScriptsTop", false)
    @{Html.RenderAction("RenderNavigation", "SiteLayout");}
    @RenderBody()
    @{Html.RenderAction("RenderBottom", "SiteLayout");}

    <!-- Bootstrap core JavaScript -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="/vendor/scrollreveal/scrollreveal.min.js"></script>
    <script src="/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- Custom scripts for this template -->
    <script src="/scripts/creative.min.js"></script>    

    @*<script src="/scripts/main.js"></script>
    <!-- jQuery -->
    <script src="/scripts/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="/scripts/jquery.easing.1.3.js"></script>
    <!-- Stellar Parallax -->
    <script src="/scripts/jquery.stellar.min.js"></script>*@
    @RenderSection("ScriptsBottom", false)
</body>
</html>